apiVersion: v1
kind: Secret
metadata:
  name: cloud-static-blob-secret
  namespace: cloud-static
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "REPLACE_ME"
  AZURE_STORAGE_CONTAINER: "content"